apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: explicit-filter
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: gamussa/explicit-filter
