name: Build app image and push to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  quotes-service:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    
    name: Build (jar and docker) Demo Chat App
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'liberica'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push native image
        run: |
          ./gradlew clean bootBuildImageNative --imageName=gamussa/explicit-filter-native
          docker push gamussa/explicit-filter-native
  