name: Build app image and push to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  quotes-service:
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    
    name: Build (jar and docker) Demo Chat App
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'liberica'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build Docker Image AMD64
        run: ./gradlew bootBuildImage --imageName=gamussa/explicit-filter-amd64

      - name: Build Docker Image ARM64
        run: ./gradlew bootBuildImage --imageName=gamussa/explicit-filter-arm64 --builder docker.io/dmikusa2pivotal/builder:focal

      - name: Push to Docker Hub
        run: docker push gamussa/explicit-filter-arm64 && docker push gamussa/explicit-filter-amd64

      - name: Create multiarch manifest
        run: docker manifest create gamussa/explicit-filter --amend gamussa/explicit-filter-amd64 --amend gamussa/explicit-filter-arm64

      - name: Push Manifest to Docker Hub
        run: docker manifest push gamussa/explicit-filter
  